services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      -   db_data:/var/lib/postgresql/data 
    networks:
      - app_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql+asyncpg://myuser:mypassword@db:5432/mydatabase"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_net


volumes:
    db_data:

networks:
  app_net:
    driver: bridge