name: Deploy to Railway

on:
  push:
    branches: [main, testes]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: 14ffd80e-83a2-4c4d-a43d-8a72b61f8974
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Set DATABASE_URL in Railway
        run: railway variables --service=${{ env.SVC_ID }} --set DATABASE_URL=teste
      
      - uses: actions/checkout@v3
      - run: railway up --service=${{ env.SVC_ID }}
